M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date tis 18 okt 2022 16:55:32
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-18T16:55:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.9Y-2.4
X4.9Y-4.25
X6.8Y-2.4
X6.8Y-4.25
T0
M30
